openapi: 3.0.0
info:
  title: Game Scoreboard API
  version: 1.0.0
  description: API for player registration, login, and score tracking
servers:
  - url: http://localhost:10964/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        score:
          type: integer

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      summary: Register a new player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, password]
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Player registered
        "409":
          description: Player already exists

  /auth/login:
    post:
      summary: Login as a player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, password]
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Invalid credentials

  /players:
    get:
      summary: Get all players
      responses:
        "200":
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Player"

  /players/{id}:
    get:
      summary: Get a player by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Player data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
        "404":
          description: Player not found

    delete:
      summary: Delete player (auth required)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Player deleted
        "403":
          description: Not allowed

  /players/{id}/score:
    patch:
      summary: Update score (auth required)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [delta]
              properties:
                delta:
                  type: integer
      responses:
        "200":
          description: Score updated
        "403":
          description: Not allowed
